### ISSUE TITLE
Needle Agent crashes when opening on JB iPhone 5c (9.0.2)

### ISSUE THREAD

**Issue by stephenjgallo** [mwrlabs/needle-agent#5]
### Expected behaviour
App should open.

### Actual behaviour
Every time I click the app to launch it, it crashes. 

### Steps to reproduce
1. on a jailbroken iPhone 5c running iOS 9.0.2 install the NeedleAgent
2. try launching the NeedleAgent from the springboard
3. observe the app crash

## Environment
tried manually installing Frida for 32 bit devices. 
successfully installed the agent on a jailbroken iPhone 5s running the same iOS version (9.0.2)
perhaps it is an issue with iPhone 5c being a 32-bit arch?

#### Device iOS Version
iPhone 5c
Jailbroken
iOS 9.0.2

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Please provide us with more detailed logs from the device.

**Comment by stephenjgallo** [comment]
Do you have a recommendation on what logs to provide? Connecting the device to Xcode and viewing the logs under Devices does not show any relevant Needle Agent crash info.

**Comment by marco-lancini** [comment]
Seems to be related to https://github.com/mwrlabs/needle/issues/142, please comment on that.
Closing this now
