### ISSUE TITLE
app not installing

### ISSUE THREAD

**Issue by pentagramz** [mwrlabs/needle-agent#6]
## Issue
Error installing deb file 

Iphone 5S iOS 10.2 Jail broken

### Expected behaviour
Tell us what sho
![needle](https://cloud.githubusercontent.com/assets/7072014/25521865/d11034ca-2c1e-11e7-95f8-8793a59d394a.PNG)
uld happen.

### Actual behaviour
Tell us what happens instead.

### Steps to reproduce
1.
2.
3.

#### Device iOS Version

**Comment by marco-lancini** [comment]
Please use Cydia to install the agent
